# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-29 08:00
from __future__ import unicode_literals

import deploy.models
import deploy.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRollback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default=None, max_length=244, verbose_name='远程主机')),
                ('cur_path', models.CharField(max_length=244)),
                ('bak_path', models.CharField(max_length=244)),
                ('file_tag', models.CharField(max_length=244, verbose_name='文件标签')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='备注')),
                ('is_group', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '文件备份',
                'verbose_name_plural': '文件备份管理',
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=244, verbose_name='远程主机')),
                ('file_path', models.FileField(upload_to=deploy.models.file_upload_dir_path, verbose_name='文件上传')),
                ('remote_path', models.CharField(max_length=244, verbose_name='远程路径')),
                ('file_tag', models.CharField(max_length=244, unique=True, verbose_name='文件标签')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '文件上传管理',
                'permissions': (('view_filemanage', '查看文件管理'), ('edit_fileupload', '管理文件上传'), ('edit_filedownload', '管理文件下载')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ModuleAttchment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attchment', models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/EEXhe5M7tEDwG79YD97E6rFTTlwPh3qBjlfq84NSaysc7qXeyHQgc4mnTxBWTSbSbmTQG75pcvl46vmC', verbose_name='模块上传')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ModuleUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='模块名称')),
                ('module', models.CharField(max_length=50, verbose_name='调用模块')),
                ('module_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='模块路径')),
                ('visible', models.IntegerField(blank=True, default=0, null=True, verbose_name='可见等级')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Salt模块',
                'verbose_name_plural': 'Salt模块管理',
                'permissions': (('edit_module', '管理Salt模块'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255, unique=True, verbose_name='项目名称')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='项目')),
                ('src', models.CharField(max_length=255, verbose_name='源地址')),
                ('src_user', models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='源用户')),
                ('src_passwd', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='源密码')),
                ('path', models.CharField(max_length=255, verbose_name='项目路径')),
                ('process', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='项目进程')),
                ('salt_test', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='测试环境')),
                ('salt_group', models.CharField(max_length=255, verbose_name='正式环境')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目管理',
                'ordering': ['-id'],
                'permissions': (('view_project', '查看项目'), ('edit_project', '管理项目')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProjectRollback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='标签')),
                ('env', models.CharField(max_length=1, verbose_name='发布环境')),
            ],
            options={
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SaltGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80, unique=True, verbose_name='Salt分组')),
                ('groupname', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Salt分组',
                'verbose_name_plural': 'Salt分组管理',
                'permissions': (('edit_saltgroup', '管理Salt主机分组'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SaltHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=80, unique=True, verbose_name='主机名称')),
                ('alive', models.BooleanField(default=False, verbose_name='连通状态')),
                ('alive_time_last', models.DateTimeField(auto_now=True)),
                ('alive_time_now', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False, verbose_name='是否加入salt管理')),
            ],
            options={
                'verbose_name': 'Salt主机授权',
                'verbose_name_plural': 'Salt主机授权管理',
                'permissions': (('view_deploy', '查看主机部署'), ('edit_deploy', '管理主机部署'), ('edit_salthost', '管理Salt主机')),
                'default_permissions': (),
            },
        ),
    ]
