# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-29 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deploy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salthost',
            name='department',
            field=models.ManyToManyField(related_name='host_department_set', to='userauth.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='salthost',
            name='user_group',
            field=models.ManyToManyField(related_name='host_usergroup_set', to='userauth.UserGroup', verbose_name='所属用户组'),
        ),
        migrations.AddField(
            model_name='saltgroup',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='saltgroup_department_set', to='userauth.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='saltgroup',
            name='minions',
            field=models.ManyToManyField(related_name='salt_host_set', to='deploy.SaltHost', verbose_name='Salt主机'),
        ),
        migrations.AddField(
            model_name='saltgroup',
            name='user_group',
            field=models.ManyToManyField(related_name='group_usergroup_set', to='userauth.UserGroup', verbose_name='所属用户组'),
        ),
        migrations.AddField(
            model_name='projectrollback',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_usergroup_set', to='userauth.UserGroup', verbose_name='用户组'),
        ),
        migrations.AddField(
            model_name='moduleupload',
            name='attchment',
            field=models.ManyToManyField(related_name='module_attchment', to='deploy.ModuleAttchment', verbose_name='模块上传'),
        ),
        migrations.AddField(
            model_name='moduleupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleupload',
            name='user_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='module_usergroup_set', to='userauth.UserGroup', verbose_name='所属用户组'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filerollback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
