# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-29 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=244, verbose_name='用户')),
                ('audit_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('action', models.CharField(max_length=20, verbose_name='动作')),
                ('action_ip', models.CharField(max_length=15, verbose_name='用户IP')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '审计信息',
                'verbose_name_plural': '审计信息管理',
                'ordering': ['-audit_time'],
                'permissions': (('view_message', '查看操作记录'), ('edit_message', '管理操作记录')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='命令别名')),
                ('command', models.TextField(blank=True, verbose_name='系统命令')),
                ('is_allow', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '远程命令',
                'verbose_name_plural': '远程命令管理',
                'permissions': (('edit_remote_permission', '管理远程权限'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='目录别名')),
                ('directory', models.TextField(blank=True, verbose_name='系统目录')),
                ('is_allow', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '远程目录',
                'verbose_name_plural': '远程目录管理',
                'default_permissions': (),
            },
        ),
    ]
