# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-29 08:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.CharField(max_length=20, unique=True, verbose_name='区域代码')),
                ('area', models.CharField(max_length=50, verbose_name='区县')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityid', models.CharField(max_length=20, unique=True, verbose_name='城市代码')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IdcAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=20, verbose_name='机房名称')),
                ('idc_type', models.CharField(blank=True, max_length=20, verbose_name='机房类型')),
                ('idc_location', models.CharField(max_length=100, verbose_name='机房位置')),
                ('contract_date', models.CharField(max_length=30, verbose_name='合同时间')),
                ('idc_contacts', models.CharField(error_messages={'required': '联系电话不能为空'}, max_length=30, validators=[django.core.validators.RegexValidator(code='号码错误', message='请输入正确的电话或手机号码', regex='^[^0]\\d{6,7}$|^[1]\\d{10}$')], verbose_name='联系电话')),
                ('remark', models.TextField(blank=True, default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IDC资产信息',
                'verbose_name_plural': 'IDC资产信息管理',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceid', models.CharField(max_length=20, unique=True, verbose_name='省份代码')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ServerAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(default=None, max_length=50, unique=True, verbose_name='Salt主机')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('manufacturer', models.CharField(blank=True, max_length=20, verbose_name='厂商')),
                ('productname', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('sn', models.CharField(blank=True, max_length=20, verbose_name='序列号')),
                ('cpu_model', models.CharField(blank=True, max_length=100, verbose_name='CPU型号')),
                ('cpu_nums', models.PositiveSmallIntegerField(verbose_name='CPU线程')),
                ('memory', models.CharField(max_length=20, verbose_name='内存')),
                ('disk', models.TextField(blank=True, verbose_name='硬盘')),
                ('network', models.TextField(blank=True, verbose_name='网络接口')),
                ('os', models.CharField(blank=True, max_length=200, verbose_name='操作系统')),
                ('virtual', models.CharField(blank=True, max_length=20, verbose_name='虚拟化')),
                ('kernel', models.CharField(blank=True, max_length=200, verbose_name='内核')),
                ('shell', models.CharField(blank=True, max_length=10, verbose_name='Shell')),
                ('zmqversion', models.CharField(blank=True, max_length=10, verbose_name='ZeroMQ')),
                ('saltversion', models.CharField(blank=True, max_length=10, verbose_name='Salt版本')),
                ('locale', models.CharField(blank=True, max_length=200, verbose_name='编码')),
                ('selinux', models.CharField(blank=True, max_length=50, verbose_name='Selinux')),
                ('idc', models.CharField(blank=True, max_length=50, verbose_name='机房')),
            ],
            options={
                'verbose_name': '主机资产信息',
                'verbose_name_plural': '主机资产信息管理',
                'permissions': (('view_asset', '查看资产'), ('edit_asset', '管理资产')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_city_set', to='asset.Provinces', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='areas',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_area_set', to='asset.Cities', verbose_name='城市'),
        ),
    ]
